name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
# additionally allows a manual trigger via workflow_dispatch
on:
  workflow_dispatch:
    types: ManualUpdate
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-windows:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build Linux Executable
      run: |
      cd ${GITHUB_WORKSPACE} && python3 -m PyInstaller --onefile -w src/tcg-to-deckbox.py --add-data=src/replacements.config:.
